### ISSUE TITLE
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

### ISSUE THREAD

**Issue by wangzixin1940** [wangzixin1940/Python-Utilities#3]
An error occurred while running this command: (Windows)
```shell
pip install vosk
``` 
It like this:
```shell
Collecting cffi>=1.0 (from vosk)
  Using cached cffi-1.16.0.tar.gz (512 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User-Name\AppData\Roaming\Python\Python313\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
----------------------------------------------------------------------------------------------------------------------------------------
        File "C:\Users\User-Name\AppData\Local\Temp\pip-build-env-wqoy3kpb\overlay\Lib\site-packages\setuptools\msvc.py", line 189, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
``` 
To fix this bug:
1. Download and [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)
2. Open the downloaded EXE file.
3. Press the "Continue" button.
![image](https://github.com/user-attachments/assets/06a4fe7a-5138-415d-aa68-8d0aeaeee8fe)
4. Wait for the program to be ready.
<img width="960" alt="屏幕截图 2024-07-12 073418" src="https://github.com/user-attachments/assets/79ee9660-3d01-4b3a-8f00-5084b796f422">
5. Press the "Install" button and wait. <br />
6. Restart your system.<br />
7. Enjoy!<br />

**Comment by wangzixin1940** [comment]
This package is a bit large and requires approximately 6GiB of available disk space.
